suppressEmpty: false
confluent:
  version: 7.3.0

kafka:
  - port: 9092
    name: kafka
  # - port: 9091
  #   name: kafka1
  # - port: 9092
  #   name: kafka2
  # - port: 9093
  #   name: kafka3

zookeeper:
  - port: 2181
    name: zookeeper

sr:
  enable: true
  port: 8081
  name: schema-registry

connect:
  enable: false
  port: 8083
  name: connect

ksqldb: 
  enable: false
  port: 8088
  name: ksqldb

prometheus:
  enable: true
  port: 9090

kafdrop: 
  enable: true
  port: 9000